[package]
name = "wasm-host"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
wasmtime = "18.0.1"
clap = { version = "4.3.19", features = ["derive"] }
wasmtime-wasi = { version = "18.0.1" }
anyhow = "1.0.72"
